### ISSUE TITLE
Fails to parse nested open/close comment sequences

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/Tokenize.jl#205] opened 2022-12-14 02:45 UTC
Reproduction
```julia

julia> collect(tokenize("""mutable struct compressor
       compressionLevel::compressionLevel
       w::huffmanBitWriter
       bulkHasher::Function
       fill::Function #=(compressor, Vector{UInt8})#=::Int=#=#
       step::Function #=(compressor)::sync=#
       bool::Bool
       bestSpeed::deflateFast
       chainHead::Int
       hashHead::Vector{UInt32}
       hashPrev::Vector{UInt32}
       hashOffset::Int
       index::Int
       window::Vector{UInt8}
       windowEnd::Int
       blockStart::Int
       byteAvailable::Bool
       tokens::Vector{token}
       length::Int
       offset::Int
       maxInsertIndex::Int
       err::error
       hashMatch::Vector{UInt32}
       end"""))
24-element Vector{Tokenize.Tokens.Token}:
 1,1-1,7          KEYWORD        "mutable"
 1,8-1,8          WHITESPACE     " "
 1,9-1,14         KEYWORD        "struct"
 1,15-1,15        WHITESPACE     " "
 1,16-1,25        IDENTIFIER     "compressor"
 1,26-2,0         WHITESPACE     "\n"
 2,1-2,16         IDENTIFIER     "compressionLevel"
 2,17-2,18        OP             "::"
 2,19-2,34        IDENTIFIER     "compressionLevel"
 2,35-3,0         WHITESPACE     "\n"
 3,1-3,1          IDENTIFIER     "w"
 3,2-3,3          OP             "::"
 3,4-3,19         IDENTIFIER     "huffmanBitWriter"
 3,20-4,0         WHITESPACE     "\n"
 4,1-4,10         IDENTIFIER     "bulkHasher"
 4,11-4,12        OP             "::"
 4,13-4,20        IDENTIFIER     "Function"
 4,21-5,0         WHITESPACE     "\n"
 5,1-5,4          IDENTIFIER     "fill"
 5,5-5,6          OP             "::"
 5,7-5,14         IDENTIFIER     "Function"
 5,15-5,15        WHITESPACE     " "
 5,16-24,3        ERROR          "#=(compressor, Vector{UInt8})#=::Int=#=#\nstep::Function #=(compressor)::sync=#\nbool::Bool\nbestSpeed::deflateFast\nchainHead::Int\nhashHead::Vector{UInt32}\nhashPrev::Vector{UInt32}\nhashOffset::Int\nindex::Int\nwindow::Vector{UInt8}\nwindowEnd::Int\nblockStart::Int\nbyteAvailable::Bool\ntokens::Vector{token}\nlength::Int\noffset::Int\nmaxInsertIndex::Int\nerr::error\nhashMatch::Vector{UInt32}\nend"
 24,4-24,3        ENDMARKER      ""

julia> Meta.parse("""mutable struct compressor
       compressionLevel::compressionLevel
       w::huffmanBitWriter
       bulkHasher::Function
       fill::Function #=(compressor, Vector{UInt8})#=::Int=#=#
       step::Function #=(compressor)::sync=#
       bool::Bool
       bestSpeed::deflateFast
       chainHead::Int
       hashHead::Vector{UInt32}
       hashPrev::Vector{UInt32}
       hashOffset::Int
       index::Int
       window::Vector{UInt8}
       windowEnd::Int
       blockStart::Int
       byteAvailable::Bool
       tokens::Vector{token}
       length::Int
       offset::Int
       maxInsertIndex::Int
       err::error
       hashMatch::Vector{UInt32}
       end""")
:(mutable struct compressor
      #= none:2 =#
      compressionLevel::compressionLevel
      #= none:3 =#
      w::huffmanBitWriter
      #= none:4 =#
      bulkHasher::Function
      #= none:5 =#
      fill::Function
      #= none:6 =#
      step::Function
      #= none:7 =#
      bool::Bool
      #= none:8 =#
      bestSpeed::deflateFast
      #= none:9 =#
      chainHead::Int
      #= none:10 =#
      hashHead::Vector{UInt32}
      #= none:11 =#
      hashPrev::Vector{UInt32}
      #= none:12 =#
      hashOffset::Int
      #= none:13 =#
      index::Int
      #= none:14 =#
      window::Vector{UInt8}
      #= none:15 =#
      windowEnd::Int
      #= none:16 =#
      blockStart::Int
      #= none:17 =#
      byteAvailable::Bool
      #= none:18 =#
      tokens::Vector{token}
      #= none:19 =#
      length::Int
      #= none:20 =#
      offset::Int
      #= none:21 =#
      maxInsertIndex::Int
      #= none:22 =#
      err::error
      #= none:23 =#
      hashMatch::Vector{UInt32}
  end)

julia>
```

**Comment by KristofferC** [comment] 2022-12-14 07:03
Most of the development of the Tokenizer now happens at https://github.com/JuliaLang/JuliaSyntax.jl. So it would be:

1. Good to check if the issue still exists when using the updated tokenizer in there.
2. Change JuliaFormatter to use JuliaSyntax.jl (I think there is some converter from the node types in JuliaSyntax to the ones used by CSTParser which should make this easier, cc @c42f).
3. Also probably a good idea to just fix the issue here in this package.

**Comment by c42f** [comment] 2022-12-15 06:43
There's also a vague plan that we'll replace the `CSTParser` parser by the `JuliaSyntax` one, so that `CSTParser` can be used only as a compat layer of data structures for other packages. However getting `JuliaSyntax` into `Base` has taken precedence right at the moment. I think I'm close on that but it's a long slog against Hyrum's law :-)

For this particular issue, I can confirm it also exists in JuliaSyntax.jl (apparent differences due to `show` I think):

```julia
julia> collect(tokenize("#=#==#=#"))
2-element Vector{Tokenize.Tokens.Token}:
 1,1-1,8          ERROR          "#=#==#=#"
 1,9-1,8          ENDMARKER      ""

julia> collect(JuliaSyntax.Tokenize.tokenize("#=#==#=#"))
2-element Vector{JuliaSyntax.Tokenize.Token}:
 0-7        ErrorEofMultiComment
 8-7        EndMarker
```

**Comment by c42f** [comment] 2022-12-15 10:15
I have a fix for this incoming.

**Closed as completed** 2022-12-15 12:27 UTC
